Boekingssysteem/Boekingssysteem/Controllers/FunctieController.cs
using Boekingssysteem.Data;
using Boekingssysteem.Lib;
using Boekingssysteem.Models;
using Boekingssysteem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace Boekingssysteem.Controllers
{
    [Authorize(Roles = "admin")]
    public class FunctieController : Controller
    {
        private readonly BoekingssysteemContext _context;

        public FunctieController(BoekingssysteemContext context)
        {
            _context = context;
        }

        public ViewResult Index()
        {
            return View();
        }

        public IActionResult Toevoegen()
        {
            ViewBag.Visibility = "invisible";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Toevoegen(FunctieCRUDViewModel viewModel)
        {
            var functies = _context.Functies.ToList();
            viewModel.Functies = functies;

            foreach (var functie in viewModel.Functies)
            {
                if (viewModel.Naam.ToLower() == functie.Naam.ToLower())
                {
                    ViewBag.Class = "alert alert-danger mb-5";
                    ViewBag.Visibility = "visible";

                    return View(viewModel);
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(new Functie()
                    {
                        Naam = viewModel.Naam,
                    });

                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    Foutenlogboek.FoutLoggen(ex);
                }

            }
            return View(viewModel);
        }

        public IActionResult Overview()
        {
            FunctieCRUDViewModel viewModel = new FunctieCRUDViewModel();
            var lijstFuncties = _context.Functies.ToList();
            viewModel.lijstFuncties = lijstFuncties;

            //ViewBag.Visibility = "invisible";
            return View(viewModel);
        }

        public async Task<IActionResult> Aanpassen(int? id) 
        {
            if (id == null)
                return NotFound();

            Functie functie = _context.Functies.Where(d => d.FunctieID == id).FirstOrDefault();

            if (functie == null)
                return NotFound();

            FunctieCRUDViewModel vm = new FunctieCRUDViewModel()
            {
                FunctieID = functie.FunctieID,
                Naam = functie.Naam
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Aanpassen(int id, FunctieCRUDViewModel viewModel)
        {
            if (id != viewModel.FunctieID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Functie functie = new Functie()
                    {
                        FunctieID = viewModel.FunctieID,
                        Naam = viewModel.Naam
                    };
                    _context.Update(functie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException e)
                {
                    if (!_context.Functies.Any(d => d.FunctieID == viewModel.FunctieID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Verwijderen(int id)
        {
            Functie functie = _context.Functies.Where(d => d.FunctieID == id).FirstOrDefault();
            if (functie != null)
            {
                FunctieCRUDViewModel vm = new FunctieCRUDViewModel()
                {
                    FunctieID = id,
                    Naam = functie.Naam
                };
            }

            _context.Functies.Remove(functie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Overview));
        }
    }
}

Boekingssysteem/Boekingssysteem/Controllers/GebruikerController.cs
using Boekingssysteem.Areas.Identity.Data;
using Boekingssysteem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;
using Boekingssysteem.Models;
using Boekingssysteem.Data;
using System;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace Boekingssysteem.Controllers
{
    [Authorize(Roles = "admin")]
    public class GebruikerController : Controller
    {
        private readonly BoekingssysteemContext _context;
        private UserManager<CustomUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;

        public GebruikerController(UserManager<CustomUser> userManager, RoleManager<IdentityRole> roleManager, BoekingssysteemContext context)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;
        }

        public IActionResult Index()
        {
            GebruikerListViewModel viewModel = new GebruikerListViewModel()
            {
                Gebruikers = _userManager.Users.ToList(),
                Roles = _context.Personen.ToList()
            };
            return View(viewModel);
        }

        public IActionResult Details(string id)
        {
            CustomUser gebruiker = _userManager.Users.Where(k => k.Id == id).FirstOrDefault();
            if (gebruiker != null)
            {
                GebruikerDetailsViewModel viewModel = new GebruikerDetailsViewModel()
                {
                    Id = gebruiker.Id,
                    Naam = gebruiker.Naam,
                    UserName = gebruiker.UserName,
                    Voornaam = gebruiker.Voornaam,
                    Personeelnummer = gebruiker.Personeelnummer,
                };
                return View(viewModel);
            }
            else
            {
                GebruikerListViewModel viewModel = new GebruikerListViewModel()
                {
                    Gebruikers = _userManager.Users.ToList()
                };
                return View("Index", viewModel);
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGebruikerViewModel viewModel)
        {
            if (viewModel.Personeelnummer.Length != 8)
            {

            }
            if (ModelState.IsValid)
            {
                CustomUser gebruiker = new CustomUser
                {
                    Naam = viewModel.Naam,
                    Voornaam = viewModel.Voornaam,
                    Personeelnummer = viewModel.Personeelnummer,
                    UserName = viewModel.Email,
                    Email = viewModel.Email
                };

                if (gebruiker.Personeelnummer.Length != 8 && viewModel.Personeelnummer.Length != 8)
                {
                    ModelState.AddModelError("", "Personeelsnummer moet minstens 8 tekens bevatten");
                }
                else
                {
                    _context.Add(new Persoon()
                    {
                        Naam = viewModel.Naam,
                        Voornaam = viewModel.Voornaam,
                        Personeelnummer = viewModel.Personeelnummer,
                        Wachtwoord = viewModel.Password,
                        Admin = false
                    });
                    await _context.SaveChangesAsync();



                    IdentityResult result = await _userManager.CreateAsync(gebruiker, viewModel.Password);
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                    {
                        foreach (IdentityError error in result.Errors)
                            ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(viewModel);
        }



        public async Task<IActionResult> Delete(string id)
        {

            CustomUser user = await _userManager.FindByIdAsync(id);

            if (user != null)
            {
                Persoon persoon = await _context.Personen.FindAsync(user.Personeelnummer);
                _context.Personen.Remove(persoon);
                await _context.SaveChangesAsync();
            }

            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    foreach (IdentityError error in result.Errors)
                        ModelState.AddModelError("", error.Description);
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View("Index", _userManager.Users.ToList());
        }

        public IActionResult GrantPermissions()
        {
            GrantPermissionsViewModel viewModel = new GrantPermissionsViewModel()
            {
                Gebruikers = new SelectList(_userManager.Users.ToList(), "Id", "UserName"),
                Rollen = new SelectList(_roleManager.Roles.ToList(), "Id", "Name")
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GrantPermissions(GrantPermissionsViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                CustomUser users = await _userManager.FindByIdAsync(viewModel.GebruikerId);
                IdentityRole roles = await _roleManager.FindByIdAsync(viewModel.RolId);
                string personeelnummer = _userManager.Users.Where(k => k.Id == viewModel.GebruikerId).Select(k => k.Personeelnummer).FirstOrDefault();
                Persoon persoon = await _context.Personen.FindAsync(personeelnummer);
                if (users != null && roles != null)
                {
                    IdentityResult result = await _userManager.AddToRoleAsync(users, roles.Name);
                    if (roles.Name == "admin")
                    {
                        persoon.Admin = true;
                        result = await _userManager.RemoveFromRoleAsync(users, "user");
                    }
                    else
                    {
                        persoon.Admin = false;
                        await _context.SaveChangesAsync();
                        result = await _userManager.RemoveFromRoleAsync(users, "admin");
                    }
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                    {
                        foreach (IdentityError error in result.Errors)
                            ModelState.AddModelError("", $"Gebruiker heeft de rol {roles.Name} al");

                        viewModel.Gebruikers = new SelectList(_userManager.Users.ToList(), "Id", "UserName");
                        viewModel.Rollen = new SelectList(_roleManager.Roles.ToList(), "Id", "Name");
                    }
                }
                else 
                {
                    ModelState.AddModelError("", $"Gebruiker heeft de rol {roles.Name} al");
                }
                    
            }
            return View(viewModel);
        }

    }
}

Boekingssysteem/Boekingssysteem/Controllers/HomeController.cs
using Boekingssysteem.Areas.Identity.Data;
using Boekingssysteem.Data;
using Boekingssysteem.Lib;
using Boekingssysteem.Models;
using Boekingssysteem.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Boekingssysteem.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly BoekingssysteemContext _context;
        private readonly SignInManager<CustomUser> _signInManager;
        private readonly ILogger<HomeController> _logger;

        public HomeController(BoekingssysteemContext context, SignInManager<CustomUser> signInManager, ILogger<HomeController> logger)
        {
            _context = context;
            _signInManager = signInManager;
            _logger = logger;                         
        }

        public IActionResult Index()
        {
           _signInManager.SignOutAsync();
            return RedirectToPage("/Account/Login", new { area = "Identity" });
        }

        public IActionResult WachtwoordVergetenView()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        //[Authorize(Roles = "Admin")]
        public IActionResult AdminView()
        {
           return View();                   
        }
        //[Authorize(Roles = "User")]
        public IActionResult GebruikerView()
        {                  
                return View();            
        }

        public IActionResult Status()
        {
            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new Models.ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(string personeelnummer, string wachtwoord)
        {
            ViewBag.Visibility = "invisible";

            bool gevonden = false;
            var lijstPersonen = _context.Personen.ToList();

            foreach (var persoon in lijstPersonen)
            {
                if (persoon.Personeelnummer == personeelnummer && persoon.Wachtwoord == wachtwoord)
                {
                    gevonden = true;
                }
            }
            try
            {
                if (gevonden)
                {
                    return RedirectToAction("GebruikerView");
                }
                else
                {
                    ViewBag.Class = "alert alert-danger mb-5";
                    ViewBag.Visibility = "visible";

                    return View();
                }

            }
            catch (Exception e)
            {
                Foutenlogboek.FoutLoggen(e);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AanpassenViaId(string personeelnummer, string wachtwoord)
        {
            var persoon = _context.Personen.FirstOrDefault(p => p.Personeelnummer == personeelnummer);

            if (persoon != null && wachtwoord != string.Empty)
            {
                try
                {
                    //int wachtwoordhash = wachtwoord.GetHashCode();
                    persoon.Wachtwoord = wachtwoord;
               
                    _context.Update(persoon);
                    await _context.SaveChangesAsync();
                    return View("Index");
                }
                catch (Exception e)
                {
                    Foutenlogboek.FoutLoggen(e);
                }
            }

            return View("Index");
        }
    }
}

Boekingssysteem/Boekingssysteem/Controllers/TVController.cs
using Boekingssysteem.Data;
using Boekingssysteem.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Boekingssysteem.Controllers
{
    public class TVController : Controller
    {
        private readonly BoekingssysteemContext _context;

        public TVController(BoekingssysteemContext context)
        {
            _context = context;
        }     

        public async Task <IActionResult> Index()
        {
            var personen = _context.Personen.ToList();           
            var persoonrichtingen = _context.PersoonRichtingen.Include(x => x.Persoon).Include(z => z.Richting);
            var persoonfuncties = _context.PersoonFuncties.Include(x => x.Persoon).Include(z => z.Functie);
            var richtingen = _context.Richtingen;
            var afwezigheden = _context.Afwezigheden;

            PersoonListViewModel plvm = new PersoonListViewModel();
            plvm.Personen = personen;
            plvm.PersoonRichtingen = persoonrichtingen.ToList();
            plvm.PersoonFuncties = persoonfuncties.ToList();
            plvm.Richtingen = richtingen.ToList();
            plvm.Afwezigheden = afwezigheden.ToList();
          
            return View(plvm);
        }

    }
}

Boekingssysteem/Boekingssysteem/Views/Home/AdminView.cshtml
﻿@using Microsoft.AspNetCore.Identity
@using Boekingssysteem.Areas.Identity.Data

@inject SignInManager<CustomUser> SignInManager
@inject UserManager<CustomUser> UserManager

@{
    ViewData["Title"] = "Admin scherm";
}



<div class="h-100 d-flex align-items-center justify-content-center">
    <div BtnCrud>
        <div class="col">
            <div class="row">
                @if (Context.User.IsInRole("admin"))
                {
                    <div class="mb-4 mx-2">
                        <h5>Aanwezig/afwezig melden</h5>
                        <a asp-controller="Status" asp-action="Index" class="btn btn-primary btn-lg mb-2" role="button">Status pagina</a>
                    </div>
                }
                else
                {
                    <div class="mb-4 mx-2">
                        <h5>Aanwezig/afwezig melden</h5>
                        <a asp-controller="Status" asp-action="StatusIndividueel" class="btn btn-primary btn-lg mb-2" role="button">Status pagina</a>
                    </div>
                }
                <div class="mb-4 mx-2">
                    <h5>Toont het tv scherm</h5>
                    <a asp-controller="TV" asp-action="Index" class="btn btn-primary btn-lg mb-2" role="button">TV pagina</a>
                </div>
                <div class="mb-4 mx-2">
                    @if (Context.User.IsInRole("admin"))
                    {
                        <h5>Personeel beheren</h5>
                        <a asp-controller="Gebruiker" asp-action="Index" class="btn btn-primary btn-lg mb-2" role="button">Admin pagina</a>
                    }
                </div>
            </div>
            <div class="row">
                <div class="mb-4">
                    @*@if (Context.User.IsInRole(""))
                    {*@
                    @* <p>creëer/update/delete Personeel</p>*@
                    @*<a asp-controller="Persoon" asp-action="Index" class="btn btn-primary btn-lg mb-2" role="button">Personen</a>*@
                    @* }  *@
                </div>
                <div class="mb-4 mx-2">
                    @if (Context.User.IsInRole("admin"))
                    {
                        <h5>Nieuwe functie aanmaken</h5>
                        <a asp-controller="Functie" asp-action="Index" class="btn btn-primary btn-lg mb-2" role="button">Functies</a>
                    }
                </div>
                <div class="mb-4 mx-2">
                    @if (Context.User.IsInRole("admin"))
                    {
                        <h5>Nieuwe richting aanmaken</h5>
                        <a asp-controller="Richting" asp-action="Index" class="btn btn-primary btn-lg mb-2" role="button">Richtingen</a>
                    }
                </div>
                <div class="mb-4 mx-2">
                    @if (Context.User.IsInRole("admin"))
                    {
                        <h5>Afwezigheden melden</h5>
                        <a asp-controller="Afwezigheid" asp-action="Index" class="btn btn-primary btn-lg mb-2" role="button">Afwezigheden</a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Boekingssysteem/Boekingssysteem/Views/Home/GebruikerView.cshtml
@{
    ViewData["Title"] = "Gebruiker scherm";
}

<div class="h-100 d-flex align-items-center justify-content-center">
    <div BtnCrud>
        <div class="col">
            <div class="mb-5">
                <a asp-controller="Status" asp-action="Index" class="btn btn-primary btn-lg mb-2" role="button">Naar status pagina</a>
            </div>
            <div class="mb-5">
                <a asp-controller="TV" asp-action="Index" class="btn btn-primary btn-lg mb-2" role="button">Naar tv pagina</a>
            </div>            
        </div>
    </div>
</div>

Boekingssysteem/Boekingssysteem/Views/Home/Index.cshtml
@model Boekingssysteem.ViewModels.PersoonCRUDViewModel
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine
@{
    ViewData["Title"] = "Home";
}

<div class="MainWindow">
    <div class="col-md-12">
        @using (Html.BeginForm("Index", "Home", FormMethod.Post))
        {                       
                <div class="col">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label asp-for="Personeelnummer" for="text" class="form-label">Personeelnummer</label>
                        <div class="col">
                            @Html.TextBoxFor(s => s.Personeelnummer, new {@class = "form-control", @placeholder = "R-nummer"})
                        </div>
                        <div>
                            <span asp-validation-for="Personeelnummer" class="text-danger"></span>
                        </div>
                    <label asp-for="Wachtwoord" for="password" class="col-sm-4 col-form-label">Wachtwoord</label>
                    <div class="col">
                        @Html.TextBoxFor(s => s.Wachtwoord, new {@class = "form-control", @type = "password", @placeholder = "Uw wachtwoord"})
                    </div>
                    <div>
                        <span asp-validation-for="Wachtwoord" class="text-danger"></span>
                    </div>
                        <div asp-validation-summary="ModelOnly"></div>

                    
                    </div>
                </div>
                <div class="BtnHome">
                    <hr class="mb-4">
                    <input type="submit" class="btn btn-primary btn-lg mb-2" value="Inloggen">
                </div>            
        }
                               
        <div class="ActionButtonHome">
            <a class="btn btn-primary btn-lg mb-2" asp-action="WachtwoordVergetenView">
                Wachtwoord vergeten
            </a>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Boekingssysteem/Boekingssysteem/Views/Home/WachtwoordVergetenView.cshtml
@model Boekingssysteem.ViewModels.PersoonCRUDViewModel
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine
@{
    ViewData["Title"] = "Wachtwoord vergeten";
}

<div class="MainWindow">
    <div class="col-md-12">
        @using (Html.BeginForm("AanpassenViaId", "Home", FormMethod.Post))
        {
                <div class="col">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label asp-for="Personeelnummer" for="text" class="form-label">Personeelnummer</label>
                        <div class="col">
                            @Html.TextBoxFor(s => s.Personeelnummer, new {@class = "form-control", @placeholder = "R-nummer"})
                        </div>
                        <div>
                            <span asp-validation-for="Personeelnummer" class="text-danger"></span>
                        </div>
                        <div asp-validation-summary="ModelOnly"></div>

                        <label asp-for="Wachtwoord" for="text" class="col-sm-4 col-form-label">Wachtwoord</label>
                        <div class="col">
                        <input asp-for="Wachtwoord" type="password" class="form-control" id="Wachtwoord1" placeholder="Uw nieuw wachtwoord">
                        </div>
                    <div>
                        <span asp-validation-for="Wachtwoord" class="text-danger"></span>
                    </div>
                        @*<label asp-for="Wachtwoord" for="text" class="col-sm-4 col-form-label">Wachtwoord</label>
                        <div class="col">
                        <input asp-for="Wachtwoord" type="password" class="form-control" id="Wachtwoord2" placeholder="Herhaal wachtwoord">*@
                        @*</div>*@
                    </div>
                </div>
                <div class="BtnHome">
                    <hr class="mb-4">
                    <input type="submit" class="btn btn-primary btn-lg mb-2" value="Aanpassen">
                </div>
        }
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}