Boekingssysteem/Boekingssysteem/Models/Afwezigheid.cs
using System.ComponentModel.DataAnnotations;
using System;

namespace Boekingssysteem.Models
{
    public class Afwezigheid
    {
        public int AfwezigheidID { get; set; }

        [Required(ErrorMessage = "Personeelnummer moet ingevuld zijn!")]
        [MinLength(8)]
        [MaxLength(8)]
        public string Personeelnummer { get; set; }

        [Required(ErrorMessage = "Begindatum moet ingevuld zijn!")]
        [DataType(DataType.Date)]
        public DateTime Begindatum { get; set; }

        [DataType(DataType.Date)]
        public DateTime? Einddatum { get; set; }

        //Navigatieproperty
        public virtual Persoon Persoon { get; set; }
    }
}

Boekingssysteem/Boekingssysteem/Controllers/AfwezigheidController.cs
using Boekingssysteem.Data;
using Boekingssysteem.Lib;
using Boekingssysteem.Models;
using Boekingssysteem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Boekingssysteem.Controllers
{
    [Authorize(Roles = "admin")]
    public class AfwezigheidController : Controller
    {
        private readonly BoekingssysteemContext _context;

        public AfwezigheidController(BoekingssysteemContext context)
        {
            _context = context;
        }
        public ViewResult Index()
        {
            return View();
        }

        public IActionResult Toevoegen()
        {
            var personen = _context.Personen.ToList();
            AfwezigheidCRUDViewModel plvm = new AfwezigheidCRUDViewModel();
            plvm.Begindatum = new DateTime(DateTime.Now.Year, 01, 01);
            plvm.Personen = personen;

            return View(plvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Toevoegen(AfwezigheidCRUDViewModel viewModel)
        {
            var personen = _context.Personen.ToList();
            viewModel.Personen = personen;

            DateTime nu = DateTime.Today;
            var afwezigheden = _context.Afwezigheden.Where(a => a.Personeelnummer == viewModel.Personeelnummer);

            Persoon persoon = _context.Personen.Find(viewModel.Personeelnummer);

            if (persoon == null)
            {
                ViewBag.Message = "Deze personeelsnummer is niet in gebruik!";
                ViewBag.Class = "alert alert-danger mb-5";
                ViewBag.Visibility = "visible";

                return View("Toevoegen", viewModel);
            }

            if (nu > viewModel.Begindatum && nu != viewModel.Begindatum)
            {
                ViewBag.Message = "Begindatum kan niet in het verleden liggen!";
                ViewBag.Class = "alert alert-danger mb-5";
                ViewBag.Visibility = "visible";
                if (viewModel.Begindatum.Year == 1)
                {
                    ViewBag.Visibility = "invisible";
                }
                return View("Toevoegen", viewModel);
            }
            if (viewModel.Begindatum > viewModel.Einddatum)
            {
                ViewBag.Message = "Begindatum moet voor de einddatum liggen!";
                ViewBag.Class = "alert alert-danger mb-5";
                ViewBag.Visibility = "visible";

                return View("Toevoegen", viewModel);
            }

            foreach (var afwezigheid in afwezigheden)
            {
                if (viewModel.Einddatum == null && viewModel.Begindatum == afwezigheid.Begindatum)
                {
                    ViewBag.Message = "Deze afwezigheid is al geregistreerd!";
                    ViewBag.Class = "alert alert-danger mb-5";
                    ViewBag.Visibility = "visible";

                    return View("Toevoegen", viewModel);
                }

                if (viewModel.Begindatum >= afwezigheid.Begindatum && viewModel.Begindatum <= afwezigheid.Einddatum)
                {
                    ViewBag.Message = "Er is deze periode al een afwezigheid geregistreerd, gelieve deze aan te passen";
                    ViewBag.Class = "alert alert-danger mb-5";
                    ViewBag.Visibility = "visible";

                    return View("Toevoegen", viewModel);
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(new Afwezigheid()
                    {
                        Personeelnummer = viewModel.Personeelnummer,
                        Begindatum = viewModel.Begindatum,
                        Einddatum = viewModel.Einddatum
                    });

                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    Foutenlogboek.FoutLoggen(ex);
                }

            }
            else
            {
                ViewBag.Message = "Gelieve minstens een begindatum in te voeren!";
                ViewBag.Class = "alert alert-danger mb-5";
                ViewBag.Visibility = "visible";

                return View("Toevoegen", viewModel);
            }
            return View("Toevoege", viewModel);
        }

        public IActionResult Aanpassen()
        {
            var personen = _context.Personen.ToList();
            AfwezigheidCRUDViewModel acvm = new AfwezigheidCRUDViewModel();
            acvm.Personen = personen;
            ViewBag.Afwezigheden = "";

            return View(acvm);
        }

        [HttpPost]
        public IActionResult Aanpassen(AfwezigheidCRUDViewModel viewModel)
        {
            var personen = _context.Personen.ToList();
            Persoon persoon = _context.Personen.Find(viewModel.Personeelnummer);
            viewModel.Personen = personen;
            ViewBag.Afwezigheden = _context.Afwezigheden.Where(a => a.Personeelnummer == viewModel.Personeelnummer).OrderBy(a => a.Begindatum);

            return View(viewModel);
        }

        public async Task<IActionResult> AanpassenDetail(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var afwezigheid = await _context.Afwezigheden.FindAsync(id);
            if (afwezigheid == null)
            {
                return NotFound();
            }

            AfwezigheidCRUDViewModel viewModel = new AfwezigheidCRUDViewModel()
            {
                AfwezigheidID = afwezigheid.AfwezigheidID,
                Begindatum = afwezigheid.Begindatum,
                Einddatum = afwezigheid.Einddatum,
                Personeelnummer = afwezigheid.Personeelnummer
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AanpassenDetail(int id, AfwezigheidCRUDViewModel viewModel)
        {
            if (id != viewModel.AfwezigheidID)
            {
                return NotFound();
            }

            DateTime nu = DateTime.Now;
            var afwezigheden = _context.Afwezigheden.Where(a => a.Personeelnummer == viewModel.Personeelnummer);

            if (nu > viewModel.Begindatum && nu != viewModel.Begindatum)
            {
                ViewBag.Message = "Begindatum kan niet in het verleden liggen!";
                ViewBag.Class = "alert alert-danger mb-5";
                ViewBag.Visibility = "visible";
                return View(nameof(Toevoegen));
            }
            if (viewModel.Begindatum > viewModel.Einddatum)
            {
                ViewBag.Message = "Begindatum moet voor de einddatum liggen!";
                ViewBag.Class = "alert alert-danger mb-5";
                ViewBag.Visibility = "visible";
                return View(nameof(Toevoegen));
            }

            foreach (var afwezigheid in afwezigheden)
            {
                if (viewModel.Einddatum == null && viewModel.Begindatum == afwezigheid.Begindatum)
                {
                    ViewBag.Message = "Deze afwezigheid is al geregistreerd!";
                    ViewBag.Class = "alert alert-danger mb-5";
                    ViewBag.Visibility = "visible";
                    return View(nameof(Toevoegen));
                }

                if (viewModel.Begindatum >= afwezigheid.Begindatum && viewModel.Begindatum <= afwezigheid.Einddatum)
                {
                    ViewBag.Message = "Er is deze periode al een afwezigheid geregistreerd, gelieve deze aan te passen";
                    ViewBag.Class = "alert alert-danger mb-5";
                    ViewBag.Visibility = "visible";
                    return View(nameof(Toevoegen));
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Afwezigheid afwezigheid = new Afwezigheid()
                    {
                        AfwezigheidID = viewModel.AfwezigheidID,
                        Begindatum = viewModel.Begindatum,
                        Einddatum = viewModel.Einddatum,
                        Personeelnummer = viewModel.Personeelnummer
                    };

                    _context.Update(afwezigheid);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Afwezigheden.Any(e => e.AfwezigheidID == viewModel.AfwezigheidID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Aanpassen));
            }

            return RedirectToAction(nameof(Aanpassen));
        }

        public async Task<IActionResult> Verwijderen(string personeelnummer, int id)
        {
            Afwezigheid afwezigheid = _context.Afwezigheden.Where(d => d.AfwezigheidID == id).FirstOrDefault();
            if (afwezigheid != null)
            {
                AfwezigheidCRUDViewModel vm = new AfwezigheidCRUDViewModel()
                {
                    AfwezigheidID = id
                };
            }

            _context.Afwezigheden.Remove(afwezigheid);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Aanpassen));
        }
    }
}

Boekingssysteem/Boekingssysteem/Views/Afwezigheid/Aanpassen.cshtml
@model Boekingssysteem.ViewModels.AfwezigheidCRUDViewModel

@{
    ViewData["Title"] = "Afwezigheid aanpassen";
}

<div class="row mb-5">
    <a class="btn btn-primary btn-lg mb-5" asp-controller="Afwezigheid" asp-action="Index">Terug</a>
    <hr />
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
        Personeel lijst
    </button>
</div>

@if (Model != null)
{
    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Personeel lijst</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @if (Model.Personen != null)
                    {
                        @foreach (var item in Model.Personen)
                        {
                            <table>
                                @using (Html.BeginForm("Aanpassen", "Afwezigheid", new { @personeelnummer = $"{@item.Personeelnummer}" }, FormMethod.Post))
                                {
                                    <input type="submit" class="btn btn-primary btn mb-2" value="@item.Personeelnummer @item.Naam @item.Voornaam">
                                }
                                <div class="divider mb-5 mt-5"></div>
                            </table>
                        }
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="h-100 d-flex align-items-center justify-content-center">
    <div BtnCrud>
        <div class="col-sm-12">
            <div class="mb-5">
                @using (Html.BeginForm())
                {
                    @Html.TextBoxFor(s => s.Personeelnummer)
                    <input class="btn btn-primary mb-2" type="submit" value="Zoek adhv personeelsnummer" />
                }
            </div>
            <div class="@ViewBag.Class @ViewBag.Visibility" role="alert">
                @ViewBag.Message
            </div>

            <table class="table table-bordered table-striped">
                <tr>
                    <th>Begindatum</th>
                    <th>Einddatum</th>
                    <th></th>
                    <th></th>
                </tr>
                @foreach (var afwezig in ViewBag.Afwezigheden)
                {
                    <tr>
                        <td>@String.Format("{0:dd/MM/yyyy}",@afwezig.Begindatum)</td>
                        <td>
                            @if (@afwezig.Einddatum != null)
                            {
                                @String.Format("{0:dd/MM/yyyy}",@afwezig.Einddatum)
                            }
                        </td>
                        <td><a class="button" asp-action="AanpassenDetail" asp-route-id="@afwezig.AfwezigheidID">Aanpassen</a></td>
                        <td><a class="button" asp-action="Verwijderen" asp-route-id="@afwezig.AfwezigheidID">Verwijderen</a></td>
                    </tr>
                }
            </table>

        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Boekingssysteem/Boekingssysteem/Views/Afwezigheid/AanpassenDetail.cshtml
@model Boekingssysteem.ViewModels.AfwezigheidCRUDViewModel

@{
    ViewData["Title"] = "Afwezigheid ingeven";
}

<div class="row mb-5">
    <a class="btn btn-primary btn-lg mb-5" asp-controller="Afwezigheid" asp-action="Index">Terug</a>
    <hr />
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
        Personeel lijst
    </button>
</div>

@if (Model != null)
{
    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Personeel lijst</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @if (Model.Personen != null)
                    {
                        @foreach (var item in Model.Personen)
                        {
                            <table>
                                @using (Html.BeginForm("AanpassenDetail", "Afwezigheid", new { @personeelnummer = $"{@item.Personeelnummer}" }, FormMethod.Post))
                                {
                                    <input type="submit" class="btn btn-primary btn mb-2" value="@item.Personeelnummer @item.Naam @item.Voornaam">
                                }
                                <div class="divider mb-5 mt-5"></div>
                            </table>
                        }
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="h-100 d-flex align-items-center justify-content-center">
    <div BtnCrud>
        <div class="col-sm-12">
            <div class="mb-5">
                <form asp-action="AanpassenDetail">
                    <div class="@ViewBag.Class @ViewBag.Visibility" role="alert">
                        @ViewBag.Message
                    </div>
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="AfwezigheidID" />
                    <input type="hidden" asp-for="Personeelnummer" />
                    <div class="form-group row">
                        <label asp-for="Begindatum" class="col-sm-4 col-form-label">Begindatum</label>
                        <div class="col-sm-10">
                            <input class="form-control" type"date" data-val="true" asp-for="Begindatum" />
                            <span asp-validation-for="Begindatum" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Einddatum" class="col-sm-4 col-form-label">EindDatum</label>
                        <div class="col-sm-10">
                            <input class="form-control" type"date" data-val="true" asp-for="Einddatum" />
                            <span asp-validation-for="Einddatum" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" value="Aanpassen" class="btn btn-primary mt-4">Aanpassen</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Boekingssysteem/Boekingssysteem/Views/Afwezigheid/Index.cshtml
@{
    ViewData["Title"] = "Afwezigheidbeheer";
}

<a class="btn btn-primary btn-lg mb-5" asp-controller="Home" asp-action="AdminView">Terug</a>
<hr />
<div class="h-100 d-flex align-items-center justify-content-center">
    <div BtnCrud>
        <div class="col">
            <div class="mb-5">
                <a asp-controller="Afwezigheid" asp-action="Toevoegen" class="btn btn-primary btn-lg mb-2" role="button">Afwezigheid ingeven</a>
            </div>
            <div class="mb-5">
                <a asp-controller="Afwezigheid" asp-action="Aanpassen" class="btn btn-primary btn-lg mb-2" role="button">Afwezigheid wijzigen/verwijderen</a>
            </div>
        </div>
    </div>
</div>

Boekingssysteem/Boekingssysteem/Views/Afwezigheid/Toevoegen.cshtml
@model Boekingssysteem.ViewModels.AfwezigheidCRUDViewModel

@{
    ViewData["Title"] = "Afwezigheid ingeven";
}

<div class="row mb-5">
    <a class="btn btn-primary btn-lg mb-5" asp-controller="Afwezigheid" asp-action="Index">Terug</a>
    <hr />
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
        Personeel lijst
    </button>
</div>

@if (Model != null)
{
    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Personeel lijst</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @if (Model.Personen != null)
                    {
                        @foreach (var item in Model.Personen)
                        {
                            <table>
                                @using (Html.BeginForm("Toevoegen", "Afwezigheid", new { @personeelnummer = $"{@item.Personeelnummer}" }, FormMethod.Post))
                                {
                                    <input type="submit" class="btn btn-primary btn mb-2" value="@item.Personeelnummer @item.Naam @item.Voornaam">
                                }
                                <div class="divider mb-5 mt-5"></div>
                            </table>
                        }
                    }                   
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="h-100 d-flex align-items-center justify-content-center">
    <div BtnCrud>
        <div class="col-sm-12">
            <div class="mb-5">
                <div class="@ViewBag.Class @ViewBag.Visibility" role="alert">
                    @ViewBag.Message
                </div>
                <form asp-action="Toevoegen">
                    
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group row">
                        <label asp-for="Personeelnummer" class="col-sm-4 col-form-label">Personeelnummer</label>
                        <div class="col-sm-10">
                            <input asp-for="Personeelnummer" class="form-control" id="Personeelnummer" placeholder="">
                            <span asp-validation-for="Personeelnummer" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Begindatum" class="col-sm-4 col-form-label">Begindatum</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="date" data-val="true" asp-for="Begindatum" />
                            <span asp-validation-for="Begindatum" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Einddatum" class="col-sm-4 col-form-label">Einddatum</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="date" data-val="true" asp-for="Einddatum" />
                            <span asp-validation-for="Einddatum" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" value="Toevoegen" class="btn btn-primary mt-4">Toevoegen</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}