Boekingssysteem/Boekingssysteem/Controllers/StatusController.cs
using Boekingssysteem.Data;
using Boekingssysteem.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Threading.Tasks;
using Boekingssysteem.Models;
using Boekingssysteem.Lib;
using System;
using static Boekingssysteem.Areas.Identity.Pages.Account.ExternalLoginModel;
using System.ComponentModel.DataAnnotations;
using Boekingssysteem.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;


namespace Boekingssysteem.Controllers
{
    public class StatusController : Controller
    {
        private readonly BoekingssysteemContext _context;
        private readonly ILogger<StatusController> _logger;
        private UserManager<CustomUser> _userManager;

        public StatusController(ILogger<StatusController> logger, BoekingssysteemContext context, UserManager<CustomUser> userManager)
        {
            _context = context;
            _logger = logger;
            _userManager = userManager;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {         
            [Display(Name = "Personeelnummer moet ingevuld zijn")]
            public string Personeelnummer { get; set; }
        }

        public ViewResult Index()
        {            
            var personen = _context.Personen.ToList();
            var persoonrichtingen = _context.PersoonRichtingen.Include(x => x.Persoon).Include(z => z.Richting);
            var persoonfuncties = _context.PersoonFuncties.Include(x => x.Persoon).Include(z => z.Functie);
            PersoonListViewModel plvm = new PersoonListViewModel();
            plvm.Personen = personen;
            plvm.PersoonRichtingen = persoonrichtingen.ToList();
            plvm.PersoonFuncties = persoonfuncties.ToList();

            return View(plvm);
        }

        public IActionResult StatusAdmin()
        {
            var personen = _context.Personen.ToList();
            PersoonCRUDViewModel plvm = new PersoonCRUDViewModel();
            plvm.Personen = personen;

            return View(plvm);
        }

        public async Task<IActionResult> StatusAanpassen(PersoonCRUDViewModel vm)
        {
            string personeelsnummer = vm.Personeelnummer;

            if (personeelsnummer == null)
            {
                return NotFound();
            }

            var persoon = await _context.Personen.FindAsync(personeelsnummer);
            if (persoon == null)
            {
                return NotFound();
            }

            if (persoon.Aanwezig == null)
            {
                PersoonCRUDViewModel viewModel = new PersoonCRUDViewModel()
                {
                    Aanwezig = true
                };
                await _context.SaveChangesAsync();
                return View(viewModel);
            }
            else if (persoon.Aanwezig == true)
            {
                PersoonCRUDViewModel viewModel = new PersoonCRUDViewModel()
                {
                    Aanwezig = false
                };
                await _context.SaveChangesAsync();
                return View(viewModel);
            }
            else
            {
                PersoonCRUDViewModel viewModel = new PersoonCRUDViewModel()
                {
                    Aanwezig = true
                };
                await _context.SaveChangesAsync();
                return View(viewModel);
            }

            return View();
        }

        public IActionResult StatusData(string personeelnummer)
        {
            var personen = _context.Personen.ToList();
            PersoonCRUDViewModel plvm = new PersoonCRUDViewModel();
            plvm.Personen = personen;

            try
            {
                Persoon persoon = _context.Personen.Find(personeelnummer);
                if (persoon == null)
                {
                    ModelState.AddModelError(string.Empty, "Het personeelnummer is onjuist");
                }
                else
                {
                    ViewBag.naam = persoon.Naam;
                    ViewBag.voornaam = persoon.Voornaam;
                    ViewBag.personeelnummer = persoon.Personeelnummer;
                    ViewBag.Aanwezig = persoon.Aanwezig;                    
                }

                return View("StatusAdmin", plvm);
            }
            catch (Exception e)
            {

                Foutenlogboek.FoutLoggen(e);
            }
            return View();
        }

        [HttpPost, ActionName("Aanpassen")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Aanpassen(string personeelnummer, PersoonCRUDViewModel viewModel)
        {
            if (personeelnummer == null)
            {
                return NotFound();
            }
            else
            {
                try
                {
                    Persoon persoon = _context.Personen.Find(personeelnummer);
                    if (persoon.Aanwezig == true)
                    {
                        persoon.Aanwezig = false;

                        _context.Update(persoon);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        persoon.Aanwezig = true;
                        _context.Update(persoon);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Personen.Any(e => e.Personeelnummer == viewModel.Personeelnummer))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

            }
            ViewBag.JavaScriptFunction = string.Format("MeldingSucces('{0}');", personeelnummer);
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("AanpassenViaId")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AanpassenViaId(string personeelnummer, PersoonCRUDViewModel viewModel)
        {            
            if (personeelnummer == null)
            {
                ModelState.AddModelError(string.Empty, "Het personeelnummer is onjuist");
            }
            else
            {
                try
                {
                    Persoon persoon = _context.Personen.Find(personeelnummer);                    
                    if (persoon.Aanwezig == true)
                    {
                        persoon.Aanwezig = false;

                        _context.Update(persoon);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        persoon.Aanwezig = true;
                        _context.Update(persoon);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Personen.Any(e => e.Personeelnummer == viewModel.Personeelnummer))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

            }                           
                ViewBag.JavaScriptFunction = string.Format("MeldingSucces('{0}');", personeelnummer);
                return RedirectToAction("StatusAdmin");           
        }

        [HttpGet]
        public IActionResult StatusIndividueel()
        {
            CustomUser user = _userManager.Users.Where(u => u.Email == User.Identity.Name).FirstOrDefault();
            Persoon persoon = _context.Personen.Where(p => p.Personeelnummer == user.Personeelnummer).FirstOrDefault();

            PersoonCRUDViewModel viewModel = new PersoonCRUDViewModel()
            {
                Voornaam = persoon.Voornaam,
                Naam = persoon.Naam,
                Personeelnummer = persoon.Personeelnummer,
                Aanwezig = persoon.Aanwezig
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> StatusIndividueel(PersoonCRUDViewModel viewModel) 
        {
            CustomUser user = _userManager.Users.Where(u => u.Email == User.Identity.Name).FirstOrDefault();
            Persoon persoon = _context.Personen.Where(p => p.Personeelnummer == user.Personeelnummer).FirstOrDefault();

            if (persoon.Aanwezig == true)
            {
                persoon.Aanwezig = false;
            }
            else
            {
                persoon.Aanwezig = true;
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(StatusIndividueel));
        }
    }
}

Boekingssysteem/Boekingssysteem/Views/Status/Index.cshtml
@model Boekingssysteem.ViewModels.PersoonListViewModel
@using Microsoft.AspNetCore.Identity
@using Boekingssysteem.Areas.Identity.Data

@inject SignInManager<CustomUser> SignInManager
@inject UserManager<CustomUser> UserManager
@{
    ViewData["Title"] = "Registratie aanwezigheid";
    <meta http-equiv="refresh" content="10">
}

@if (SignInManager.IsSignedIn(User))
{
    <a class="btn btn-primary btn-lg mb-5" asp-controller="Home" asp-action="AdminView">Terug</a>
}
else
{
    <a class="btn btn-primary btn-lg mb-5" asp-controller="Home" asp-action="GebruikerView">Terug</a>
}   

<hr />
<div class="StatusWindow">
    <div class="container">
        <div class="mb-5">
            @if (Context.User.IsInRole("admin"))
            {
                <a asp-controller="Status" asp-action="StatusAdmin" class="btn btn-primary btn-lg mb-2" role="button">Aanwezigheid aanpassen</a>
            }            
        </div>                   
            @foreach (var p in Model.Personen)
            {
            @using (Html.BeginForm("Aanpassen", "Status", new { @personeelnummer = $"{p.Personeelnummer}" }, FormMethod.Post))
            {
                <div class="row">
                    <div class="col">
                        @Html.DisplayFor(modelItem => p.Naam)
                        @Html.DisplayFor(modelItem => p.Voornaam)
                    </div>

                    @if (p.PersoonRichtingen == null)
                    {
                        <div class="col">Geen richting</div>
                    }
                    else
                    {

                        <div class="col">

                            @foreach (var item in p.PersoonRichtingen)
                            {
                                @Html.DisplayFor(modelItem => item.Richting.Naam) <br>
                            }

                            @if (p.Admin)
                            {
                                <p>Administratief personeel</p>
                            }
                            else
                            {
                                <p>Leerkracht</p>
                            }
                        </div>
                    }

                    <div class="row">
                        <div class="col">
                            @if (p.Aanwezig == true)
                            {
                                <p style="color: green; font-size:20px">Aanwezig</p>
                            }
                            else if (p.Aanwezig == false)
                            {
                                <p style="color: red; font-size:20px">Afwezig</p>
                            }
                            else
                            {
                                <p style="color: #e6b400; font-size:20px">Ongekend</p>
                            }
                        </div>

                        <div class="col">
                            <form>
                                @using (Html.BeginForm("AanpassenViaId", "Status", new { @personeelnummer = $"{@p.Personeelnummer}" }, FormMethod.Post))
                                {
                                <div asp-validation-summary="ModelOnly"></div>                                
                                <input type="submit" class="btn btn-primary btn-lg mb-2" value="Status aanpassen">                                                                
                                }
                            </form>
                        </div>                   
                    </div>
                </div>
                <div class="divider mt-5 mb-5"></div>
            }
        }          
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Boekingssysteem/Boekingssysteem/Views/Status/StatusAdmin.cshtml
@model Boekingssysteem.ViewModels.PersoonCRUDViewModel
@{
    ViewData["Title"] = "Aanwezigheid aanpassen admin";
}

<div class="row mb-5">
    @if (Context.User.IsInRole("admin"))
    {
        <a class="btn btn-primary btn-lg mb-5" asp-controller="Status" asp-action="Index">Terug</a>
    }
    else
    {
        <a class="btn btn-primary btn-lg mb-5" asp-controller="Home" asp-action="AdminView">Terug</a>
    }   
    <hr />
    @if (Context.User.IsInRole("admin"))
    {
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
            Personeel lijst
        </button>
    }   
</div>

@if (Model != null)
{
    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Personeellijst</h5>
                    <button type="button" class="close @ViewBag.Visibility" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @if (Model.Personen != null)
                    {
                        @foreach (var item in Model.Personen)
                        {
                            <table>
                                @using (Html.BeginForm("StatusData", "Status", new { @personeelnummer = $"{@item.Personeelnummer}" }, FormMethod.Post))
                                {
                                    <input type="submit" class="btn btn-primary btn mb-2" value="@item.Personeelnummer @item.Naam @item.Voornaam">
                                }                                                    
                                <div class="divider mb-5 mt-5"></div>
                            </table>
                        }
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="h-100 d-flex align-items-center justify-content-center">
    <div class="col">
        <div asp-validation-summary="All" class="text-danger"></div>
        @using (Html.BeginForm("StatusData", "Status", FormMethod.Post))
        {            
            <form>
                <div class="col">
                    <div class="mb-5">
                        <div class="form-group">
                            <label class="mr-3">Personeelsnummer: </label>
                            @Html.TextBoxFor(s => s.Personeelnummer, new {@class = "form-control mb-3", @placeholder = ""})
                            <input type="submit" value="Gebruiker zoeken" class="btn btn-primary mb-2" />
                            <span asp-validation-for="Personeelnummer" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="PersoneelInfo">
                        <div class="col">
                            <div class="row">
                                <p>Naam: @ViewBag.naam</p>
                            </div>
                            <div class="row">
                                <p>Voornaam: @ViewBag.voornaam</p>

                            </div>
                            <div class="row">
                                <p>Personeelnummer: @ViewBag.personeelnummer</p>
                            </div>
                            <div class="row">
                                @if (ViewBag.Aanwezig == null)
                                {
                                    <p>Status: Ongekend</p>
                                }
                                else if (ViewBag.Aanwezig == true)
                                {
                                    <p>Status: Aanwezig</p>
                                }
                                else
                                {
                                    <p>Status: Afwezig</p>
                                }
                            </div>
                        </div>
                    </div>
                </div>                
            </form>
        }       
        <div class="row">
            <div>
                @using (Html.BeginForm("AanpassenViaId", "Status", new { @personeelnummer = $"{@ViewBag.personeelnummer}" }, FormMethod.Post))
                {
                    <div class="mt-5 mr-5">
                        <input type="submit" class="btn btn-primary btn-lg mb-2" value="Status aanpassen">
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Boekingssysteem/Boekingssysteem/Views/Status/StatusIndividueel.cshtml
@model Boekingssysteem.ViewModels.PersoonCRUDViewModel
@{
    ViewData["Title"] = "Aanwezigheid aanpassen";
}

<div class="row mb-5">
    <a class="btn btn-primary btn-lg mb-5" asp-controller="Home" asp-action="AdminView">Terug</a>
</div>

<form asp-action="StatusIndividueel">
    <div class="PersoneelInfo">
        <div class="col">
            <div class="row">
                <p>Naam: @Model.Naam</p>
            </div>
            <div class="row">
                <p>Voornaam: @Model.Voornaam</p>
            </div>
            <div class="row">
                <p>Personeelnummer: @Model.Personeelnummer</p>
            </div>
            <div class="row">
                @if (@Model.Aanwezig == null)
                {
                    <p>Status: Ongekend</p>
                }
                else if (@Model.Aanwezig == true)
                {
                    <p>Status: Aanwezig</p>
                }
                else
                {
                    <p>Status: Afwezig</p>
                }
            </div>
        </div>
    </div>    
    
    <div class="form-group">
        <input type="submit" value="Status veranderen" class="btn btn-primary" />
    </div>
</form>