Boekingssysteem/Boekingssysteem/Controllers/GebruikerController.cs
using Boekingssysteem.Areas.Identity.Data;
using Boekingssysteem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;
using Boekingssysteem.Models;
using Boekingssysteem.Data;
using System;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace Boekingssysteem.Controllers
{
    [Authorize(Roles = "admin")]
    public class GebruikerController : Controller
    {
        private readonly BoekingssysteemContext _context;
        private UserManager<CustomUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;

        public GebruikerController(UserManager<CustomUser> userManager, RoleManager<IdentityRole> roleManager, BoekingssysteemContext context)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;
        }

        public IActionResult Index()
        {
            GebruikerListViewModel viewModel = new GebruikerListViewModel()
            {
                Gebruikers = _userManager.Users.ToList(),
                Roles = _context.Personen.ToList()
            };
            return View(viewModel);
        }

        public IActionResult Details(string id)
        {
            CustomUser gebruiker = _userManager.Users.Where(k => k.Id == id).FirstOrDefault();
            if (gebruiker != null)
            {
                GebruikerDetailsViewModel viewModel = new GebruikerDetailsViewModel()
                {
                    Id = gebruiker.Id,
                    Naam = gebruiker.Naam,
                    UserName = gebruiker.UserName,
                    Voornaam = gebruiker.Voornaam,
                    Personeelnummer = gebruiker.Personeelnummer,
                };
                return View(viewModel);
            }
            else
            {
                GebruikerListViewModel viewModel = new GebruikerListViewModel()
                {
                    Gebruikers = _userManager.Users.ToList()
                };
                return View("Index", viewModel);
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGebruikerViewModel viewModel)
        {
            if (viewModel.Personeelnummer.Length != 8)
            {

            }
            if (ModelState.IsValid)
            {
                CustomUser gebruiker = new CustomUser
                {
                    Naam = viewModel.Naam,
                    Voornaam = viewModel.Voornaam,
                    Personeelnummer = viewModel.Personeelnummer,
                    UserName = viewModel.Email,
                    Email = viewModel.Email
                };

                if (gebruiker.Personeelnummer.Length != 8 && viewModel.Personeelnummer.Length != 8)
                {
                    ModelState.AddModelError("", "Personeelsnummer moet minstens 8 tekens bevatten");
                }
                else
                {
                    _context.Add(new Persoon()
                    {
                        Naam = viewModel.Naam,
                        Voornaam = viewModel.Voornaam,
                        Personeelnummer = viewModel.Personeelnummer,
                        Wachtwoord = viewModel.Password,
                        Admin = false
                    });
                    await _context.SaveChangesAsync();



                    IdentityResult result = await _userManager.CreateAsync(gebruiker, viewModel.Password);
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                    {
                        foreach (IdentityError error in result.Errors)
                            ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(viewModel);
        }



        public async Task<IActionResult> Delete(string id)
        {

            CustomUser user = await _userManager.FindByIdAsync(id);

            if (user != null)
            {
                Persoon persoon = await _context.Personen.FindAsync(user.Personeelnummer);
                _context.Personen.Remove(persoon);
                await _context.SaveChangesAsync();
            }

            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    foreach (IdentityError error in result.Errors)
                        ModelState.AddModelError("", error.Description);
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View("Index", _userManager.Users.ToList());
        }

        public IActionResult GrantPermissions()
        {
            GrantPermissionsViewModel viewModel = new GrantPermissionsViewModel()
            {
                Gebruikers = new SelectList(_userManager.Users.ToList(), "Id", "UserName"),
                Rollen = new SelectList(_roleManager.Roles.ToList(), "Id", "Name")
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GrantPermissions(GrantPermissionsViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                CustomUser users = await _userManager.FindByIdAsync(viewModel.GebruikerId);
                IdentityRole roles = await _roleManager.FindByIdAsync(viewModel.RolId);
                string personeelnummer = _userManager.Users.Where(k => k.Id == viewModel.GebruikerId).Select(k => k.Personeelnummer).FirstOrDefault();
                Persoon persoon = await _context.Personen.FindAsync(personeelnummer);
                if (users != null && roles != null)
                {
                    IdentityResult result = await _userManager.AddToRoleAsync(users, roles.Name);
                    if (roles.Name == "admin")
                    {
                        persoon.Admin = true;
                        result = await _userManager.RemoveFromRoleAsync(users, "user");
                    }
                    else
                    {
                        persoon.Admin = false;
                        await _context.SaveChangesAsync();
                        result = await _userManager.RemoveFromRoleAsync(users, "admin");
                    }
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                    {
                        foreach (IdentityError error in result.Errors)
                            ModelState.AddModelError("", $"Gebruiker heeft de rol {roles.Name} al");

                        viewModel.Gebruikers = new SelectList(_userManager.Users.ToList(), "Id", "UserName");
                        viewModel.Rollen = new SelectList(_roleManager.Roles.ToList(), "Id", "Name");
                    }
                }
                else 
                {
                    ModelState.AddModelError("", $"Gebruiker heeft de rol {roles.Name} al");
                }
                    
            }
            return View(viewModel);
        }

    }
}

Boekingssysteem/Boekingssysteem/Controllers/PersoonController.cs
using Boekingssysteem.Areas.Identity.Data;
using Boekingssysteem.Data;
using Boekingssysteem.Lib;
using Boekingssysteem.Models;
using Boekingssysteem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace Boekingssysteem.Controllers
{
    [Authorize(Roles = "admin")]
    public class PersoonController : Controller
    {
        private readonly BoekingssysteemContext _context;

        private UserManager<CustomUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;

        public PersoonController(BoekingssysteemContext context, UserManager<CustomUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public ViewResult Index()
        {
            return View();
        }
        
        public IActionResult Toevoegen()
        {
            ViewBag.Visibility = "invisible";
            ViewBag.Functies = _context.Functies;
            ViewBag.Richtingen = _context.Richtingen;

            var personen = _context.Personen.ToList();
            PersoonCRUDViewModel plvm = new PersoonCRUDViewModel();
            plvm.Personen = personen;

            return View(plvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Toevoegen(PersoonCRUDViewModel viewModel, string personeelnummer, int[] FunctieIDs, int[] RichtingIDs)
        {
            ViewBag.Functies = _context.Functies;
            ViewBag.Richtingen = _context.Richtingen;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(new Persoon()
                    {
                        Personeelnummer = viewModel.Personeelnummer,
                        Naam = viewModel.Naam,
                        Voornaam = viewModel.Voornaam,
                        Admin = viewModel.Admin
                    });
                    await _context.SaveChangesAsync();

                    foreach (int ID in RichtingIDs)
                    {
                        
                        _context.Add(new PersoonRichting()
                        {
                            Personeelnummer = personeelnummer,
                            RichtingID = ID
                        });
                        await _context.SaveChangesAsync();
                    }

                    foreach (int ID in FunctieIDs)
                    {
                        _context.Add(new PersoonFunctie()
                        {
                            Personeelnummer = personeelnummer,
                            FunctieID = ID
                        });
                        
                        //_context.PersoonFuncties.Add(persFunctie);
                        await _context.SaveChangesAsync();
                    }

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    Foutenlogboek.FoutLoggen(ex);
                    ViewBag.Class = "alert alert-danger mb-5";
                    ViewBag.Visibility = "visible";
                }
            }
            return View(viewModel);
        }

        public IActionResult Aanpassen()
        {
            ViewBag.Visibility = "invisible";
            ViewBag.Functies = _context.Functies;
            ViewBag.Richtingen = _context.Richtingen;

            var personen = _context.Personen.ToList();
            PersoonCRUDViewModel plvm = new PersoonCRUDViewModel();
            plvm.Personen = personen;

            return View(plvm);
        }

        [HttpPost]
        public IActionResult Aanpassen(string personeelnummer)
        {
            ViewBag.Visibility = "invisible";
            ViewBag.Functies = _context.Functies;
            ViewBag.Richtingen = _context.Richtingen;

            bool gevonden = false;
            var lijstPersonen = _context.Personen.ToList();

            foreach (var persoon in lijstPersonen)
            {
                if (persoon.Personeelnummer == personeelnummer)
                {
                    gevonden = true;
                }
            }

            try
            {
                if (gevonden)
                {
                    Persoon persoon = _context.Personen.Find(personeelnummer);
                    PersoonCRUDViewModel viewModel = new PersoonCRUDViewModel()
                    {
                        Personeelnummer = persoon.Personeelnummer,
                        Naam = persoon.Naam,
                        Voornaam = persoon.Voornaam,
                        Admin = persoon.Admin,
                        Wachtwoord = persoon.Wachtwoord                       
                    };

                    var personen = _context.Personen.ToList();
                    viewModel.Personen = personen;

                    return View(viewModel);
                }
                else
                {
                    ViewBag.Class = "alert alert-danger mb-5";
                    ViewBag.Visibility = "visible";
                    ViewBag.Message = "Geen gebruiker gevonden met dit personeelnummer";

                    var personen = _context.Personen.ToList();
                    PersoonCRUDViewModel plvm = new PersoonCRUDViewModel();
                    plvm.Personen = personen;

                    return View(plvm);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost, ActionName("AanpassenDetail")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AanpassenDetail(string personeelnummer, PersoonCRUDViewModel viewModel, int[] FunctieIDs, int[] RichtingIDs, string userId)
        {        
            ViewBag.Functies = _context.Functies;
            ViewBag.Richtingen = _context.Richtingen;

            if (personeelnummer == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Persoon persoon = new Persoon()
                    {
                        Personeelnummer = viewModel.Personeelnummer,
                        Voornaam = viewModel.Voornaam,
                        Naam = viewModel.Naam,
                        Admin = viewModel.Admin,
                        Wachtwoord = viewModel.Wachtwoord
                    };
                                       
                    CustomUser user = _userManager.Users.Where(k => k.Personeelnummer == personeelnummer).FirstOrDefault();
                    user.Personeelnummer = personeelnummer;
                    user.Naam = viewModel.Naam;
                    user.Voornaam = viewModel.Voornaam;
                                      
                    await _userManager.UpdateAsync(user);
                    _context.Update(persoon);
                    await _context.SaveChangesAsync();

                    //Bestaande PersoonFuncties & PersoonRichtingen verwijderen
                    foreach (var persf in _context.PersoonFuncties.ToList())
                    {
                        if (persf.Personeelnummer == personeelnummer)
                        {
                            _context.PersoonFuncties.Remove(persf);
                        }
                    }
                    foreach (var persr in _context.PersoonRichtingen.ToList())
                    {
                        if (persr.Personeelnummer == personeelnummer)
                        {
                            _context.PersoonRichtingen.Remove(persr);
                        }
                    }

                    //Nieuwe PersoonFuncties & PersoonRichtingen toevoegen
                    foreach (int ID in RichtingIDs)
                    {

                        _context.Add(new PersoonRichting()
                        {
                            Personeelnummer = personeelnummer,
                            RichtingID = ID
                        });
                        await _context.SaveChangesAsync();
                    }

                    foreach (int ID in FunctieIDs)
                    {
                        _context.Add(new PersoonFunctie()
                        {
                            Personeelnummer = personeelnummer,
                            FunctieID = ID
                        });

                        //_context.PersoonFuncties.Add(persFunctie);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Personen.Any(e => e.Personeelnummer == viewModel.Personeelnummer))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Aanpassen");
            }

            return View("Aanpassen");
        }

        public IActionResult Verwijderen()
        {
            ViewBag.Enabled = "disabled";
            ViewBag.Visibility = "invisible";

            var personen = _context.Personen.ToList();
            PersoonCRUDViewModel plvm = new PersoonCRUDViewModel();
            plvm.Personen = personen;

            return View(plvm);
        }

        public IActionResult VerwijderenData(string personeelnummer)
        {
            bool gevonden = false;
            
            PersoonCRUDViewModel viewModel = new PersoonCRUDViewModel();

Boekingssysteem/Boekingssysteem/Views/Persoon/Aanpassen.cshtml
@model Boekingssysteem.ViewModels.PersoonCRUDViewModel
@{
    ViewData["Title"] = "Aanpassen";
}

<div class="row mb-5">
    <a class="btn btn-primary btn-lg mb-5" asp-controller="Gebruiker" asp-action="Index">Terug</a>
    <hr />
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
        Personeel lijst
    </button>
</div>

@if (Model != null)
{
    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Personeellijst</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @if (Model.Personen != null)
                    {
                        @foreach (var item in Model.Personen)
                        {
                            <table>
                                @using (Html.BeginForm("Aanpassen", "Persoon", new { @personeelnummer = $"{@item.Personeelnummer}" }, FormMethod.Post))
                                {
                                    <input type="submit" class="btn btn-primary btn mb-2" value="@item.Personeelnummer @item.Naam @item.Voornaam">
                                }
                                <div class="divider mb-5 mt-5"></div>
                            </table>
                        }
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="h-100 d-flex align-items-center justify-content-center">
    <div BtnCrud>
        <div class="col-sm-12">
            <div class="mb-5">
                @using (Html.BeginForm())
                {
                    @Html.TextBoxFor(s => s.Personeelnummer)
                    <input class="btn btn-primary mb-2" type="submit" value="Zoek adhv personeelsnummer" />
                    <div> <span asp-validation-for="Personeelnummer" class="text-danger"></span></div>
                }
            </div>
            <div class="@ViewBag.Class @ViewBag.Visibility" role="alert">
                @ViewBag.Message
            </div>
            <div class="mb-5">
                @using (Html.BeginForm("AanpassenDetail", "Persoon", FormMethod.Post))
                {
                    <form asp-action="AanpassenDetail">
                        <div asp-validation-summary="ModelOnly"></div>
                        <div class="form-group row">
                            <label asp-for="Personeelnummer" for="text" class="col-sm-4 col-form-label">Personeelnummer</label>
                            <div class="col-sm-10">
                                <input asp-for="Personeelnummer" type="text" class="form-control disabledTM" id="personeelnummer" placeholder="">
                            </div>
                            <span asp-validation-for="Personeelnummer" class="text-danger"></span>
                        </div>
                        <div class="form-group row">
                            <label asp-for="Naam" for="text" class="col-sm-4 col-form-label">Naam</label>
                            <div class="col-sm-10">
                                <input asp-for="Naam" type="text" class="form-control" id="naam" placeholder="">
                            </div>
                            <span asp-validation-for="Naam" class="text-danger"></span>
                        </div>
                        <div class="form-group row">
                            <label asp-for="Voornaam" for="text" class="col-sm-4 col-form-label">Voornaam</label>
                            <div class="col-sm-10">
                                <input asp-for="Voornaam" type="text" class="form-control" id="voornaam" placeholder="">
                            </div>
                            <span asp-validation-for="Voornaam" class="text-danger"></span>
                        </div>
                        <div class="form-group row">                        
                            <div class="col-sm-10">
                                <input asp-for="Wachtwoord" type="hidden" class="form-control disabledTM" id="Wachtwoord" placeholder="">
                            </div>
                        
                        </div>
                        <div class="form-group row ">
                            <div class="col-sm-6">
                                <h4 class="col-sm-4 col-form-label">Richtingen:</h4>
                                <ul>
                                    @foreach (var richting in ViewBag.Richtingen)
                                    {
                                        <li><input type="checkbox" name="RichtingIDs" value="@richting.RichtingID" class="form-check-input" />@richting.Naam</li>
                                    }
                                </ul>
                            </div>
                            <div class="col-sm-6">
                                <h4 class="col-sm-4 col-form-label">Functies:</h4>
                                <ul>
                                    @foreach (var functie in ViewBag.Functies)
                                    {
                                        <li><input type="checkbox" name="FunctieIDs" value="@functie.FunctieID" class="form-check-input" />@functie.Naam</li>
                                    }
                                </ul>
                            </div>
                        </div>  
                        
                        @*<input asp-for=Admin type="hidden" value="@Model.Admin" />*@
                        
                        @*<div class="form-group row mt-2">
                            <div class="col-sm-2">Admin</div>
                            <div class="col-sm-10">
                                <div class="form-check">
                                    <input asp-for="Admin" class="form-check-input" type="checkbox" id="gridCheck1">
                                    <label asp-for="Admin" class="form-check-label" for="gridCheck1">
                                        Selecteer om administrator te maken
                                    </label>
                                </div>
                            </div>
                        </div>*@

                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" value="Save" class="btn btn-primary mt-4">Wijzigen</button>
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Boekingssysteem/Boekingssysteem/Views/Persoon/Index.cshtml
@{
    ViewData["Title"] = "Gebruikerbeheer";
}

<a class="btn btn-primary btn-lg mb-5" asp-controller="Home" asp-action="AdminView">Terug</a>
<hr />
<div class="h-100 d-flex align-items-center justify-content-center">  
    <div BtnCrud>
        <div class="col">
            <div class="mb-5">               
                <a asp-controller="Persoon" asp-action="Toevoegen" class="btn btn-primary btn-lg mb-2" role="button">Gebruiker aanmaken</a>
            </div>
            <div class="mb-5">
                <a asp-controller="Persoon" asp-action="Aanpassen" class="btn btn-primary btn-lg mb-2" role="button">Gebruiker wijzigen</a>
            </div>
            <div class="mb-5">
                <a asp-controller="Persoon" asp-action="Verwijderen" class="btn btn-primary btn-lg mb-2" role="button">Gebruiker verwijderen</a>
            </div>           
        </div>     
    </div>  
</div>

Boekingssysteem/Boekingssysteem/Views/Persoon/Verwijderen.cshtml
@model Boekingssysteem.ViewModels.PersoonCRUDViewModel
@{
    ViewData["Title"] = "Verwijderen";
}

<div class="row mb-5">
    <a class="btn btn-primary btn-lg mb-5" asp-controller="Persoon" asp-action="Index">Terug</a>
    <hr />
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
        Personeel lijst
    </button>
</div>

@if (Model != null)
{
    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Personeel lijst</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @if (Model.Personen != null)
                    {
                        @foreach (var item in Model.Personen)
                        {
                            <table>
                                @using (Html.BeginForm("VerwijderenData", "Persoon", new { @personeelnummer = $"{@item.Personeelnummer}" }, FormMethod.Post))
                                {
                                    <input type="submit" class="btn btn-primary btn mb-2" value="@item.Personeelnummer @item.Naam @item.Voornaam">
                                }
                                <div class="divider mb-5 mt-5"></div>
                            </table>
                        }
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="h-100 d-flex align-items-center justify-content-center">
    <div class="col">               
        @using (Html.BeginForm("VerwijderenData", "Persoon", FormMethod.Post))
        {
            <div class="@ViewBag.Class @ViewBag.Visibility" role="alert">
                Niemand gevonden met dit personeelsnummer!
            </div>
            <div class="col">
                <div class="mb-5">
                    <div class="form-group">
                        <label class="mr-3">Personeelsnummer: </label>
                        <input class="mr-3" type="text" name="personeelnummer" />
                        <input type="submit" value="Gebruiker zoeken" class="btn btn-primary mb-2" />
                    </div>
                </div>
                <div class="PersoneelInfo">
                    <div class="col">
                        <div class="row">
                            <p>Naam: @ViewBag.naam</p>
                        </div>
                        <div class="row">
                            <p>Voornaam: @ViewBag.voornaam</p>
                        </div>
                        <div class="row">
                            <p>Personeelnummer: @ViewBag.personeelnummer</p>
                        </div>
                    </div>
                </div>

            </div>
        }
        @using (Html.BeginForm("Delete", "Persoon", FormMethod.Post))
        {
            <div class="mt-5">
                <form asp-action="Delete">
                    <input type="hidden" asp-for="Personeelnummer" />
                    <input type="submit" value="Gebruiker verwijderen" @ViewBag.Enabled class="btn btn-primary btn-lg mb-2" />
                </form>
            </div>
        }
    </div>
</div>